[project]
name = "high-school-python-code"
version = "0.1.0"
description = "『ハイスクールPython』で使用されているソースコードをまとめたものです"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["mypy>=1.14.1", "pytest>=8.3.4", "ruff>=0.9.1"]
